version: "3.7"

services:
  auth:
    container_name: auth
    build: ../auth
    command: ./auth
    networks:
      - traefik_proxy
    ports:
      - "8081:8081"
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.service=auth
      - traefik.http.routers.auth.rule=Host(`app.flixray.ru`) && PathPrefix(`/srv/auth`)
      - traefik.http.middlewares.auth.stripprefix.prefixes=/srv/auth
      - traefik.http.routers.auth.middlewares=auth
      - traefik.http.routers.auth.entrypoints=https
      - traefik.http.routers.auth.tls.certresolver=production
      - traefik.http.services.auth.loadbalancer.server.port=8081

networks:
  traefik_proxy:
    external: true